server:
  port: 8081
mybatis:
  type-aliases-package: com.xueqiu.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  application:
    name: springcloud-provider-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/checkdatabase?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 520560

#Eureka 的配置 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka,http://127.0.0.1:7003/eureka,http://localhost:7001/eureka
  instance:
    instance-id: springcloud-provider-user


#info配置
info:
  app.name: test-springcloud
  company.name: wyyyy
