server:
  port: 7003

#Eureka配置
eureka:
  instance:
    hostname: 127.0.0.1 #Eureka服务端的实例名称
  client:
    register-with-eureka: false  #是否像eureka注册中心注册自己
    fetch-registry: false  #fetch-registry表示如果为false 则表示自己为注册中心
    service-url:   #监控页面
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/